title: Chiyuan Cui's Homepage
page-top-title: Chiyuan Cui
top-section-bg-text: Computer Vision
home-subtitle: Chiyuan Cui&ensp;|&ensp;崔驰远
copyright-text: '&copy; Chiyuan Cui 2026. All Rights Reserved.'
